#!/bin/bash

#PBS -l select=1:ncpus=8:mem=64gb
#PBS -l walltime=24:00:00

source $(conda info --base)/etc/profile.d/conda.sh
conda activate salmon

cd /srv/scratch/vafaeelab/AbhishekVijayan/GBMPlasmaEV/Data/

for fn in trimmedRNA/*fastq.gz;
do
samp=`basename ${fn}`
echo "Processing sample ${samp}"
salmon quant -i Reference/human_alltranscriptgenome_index_k9 -l A \
         -r ${fn} \
         -p 8 --validateMappings -o quants_k9/${samp}_quant
done

for fn in trimmedRNA/*fastq.gz;
do
samp=`basename ${fn}`
echo "Processing sample ${samp}"
salmon quant -i Reference/human_alltranscriptgenome_index_k21 -l A \
         -r ${fn} \
         -p 8 --validateMappings -o quants_k21/${samp}_quant
done