#source('utils.R')
#to do - remove unnecessary calls in utils.R and make this 'source' work
#for now, manually execute the function definition before executing the function calls below


create_dim_red_plots_PMH(comparison = "PREOPEVsMET", classes = c("MET", "PREOPE"),
                         omics_type = "proteomics", norm = "none",
                         dim_red = "UMAP",
                         shownames = FALSE,
                         perform_filter = FALSE,
                         batch_effect_correction = "none",
                         plot_dir_path = "plots_comparison_set2/qc/dim_red/",
                         best_features_file_path = NA,
                         dataset_replace_str = NA,
                         file_name_prefix = 1)
create_dim_red_plots_PMH(comparison = "PREOPEVsMET", classes = c("MET", "PREOPE"),
                         omics_type = "proteomics", norm = "quantile_train_param",
                         dim_red = "UMAP",
                         shownames = FALSE,
                         perform_filter = FALSE,
                         batch_effect_correction = "none",
                         plot_dir_path = "plots_comparison_set2/qc/dim_red/",
                         best_features_file_path = NA,
                         dataset_replace_str = NA,
                         file_name_prefix = 2)
create_dim_red_plots_PMH(comparison = "PREOPEVsMET", classes = c("MET", "PREOPE"),
                         omics_type = "proteomics", norm = "quantile_train_param",
                         dim_red = "UMAP",
                         shownames = FALSE,
                         perform_filter = FALSE,
                         batch_effect_correction = "combat",
                         plot_dir_path = "plots_comparison_set2/qc/dim_red/",
                         best_features_file_path = NA,
                         dataset_replace_str = NA,
                         file_name_prefix = 3)

create_dim_red_plots_PMH(comparison = "PREOPEVsHC", classes = c("HC", "PREOPE"),
                         omics_type = "proteomics", norm = "none",
                         dim_red = "UMAP",
                         shownames = FALSE,
                         perform_filter = FALSE,
                         batch_effect_correction = "none",
                         plot_dir_path = "plots_comparison_set2/qc/dim_red/",
                         best_features_file_path = NA,
                         dataset_replace_str = NA,
                         file_name_prefix = 4)
create_dim_red_plots_PMH(comparison = "PREOPEVsHC", classes = c("HC", "PREOPE"),
                         omics_type = "proteomics", norm = "quantile_train_param",
                         dim_red = "UMAP",
                         shownames = FALSE,
                         perform_filter = FALSE,
                         batch_effect_correction = "none",
                         plot_dir_path = "plots_comparison_set2/qc/dim_red/",
                         best_features_file_path = NA,
                         dataset_replace_str = NA,
                         file_name_prefix = 5)
create_dim_red_plots_PMH(comparison = "PREOPEVsHC", classes = c("HC", "PREOPE"),
                         omics_type = "proteomics", norm = "quantile_train_param",
                         dim_red = "UMAP",
                         shownames = FALSE,
                         perform_filter = FALSE,
                         batch_effect_correction = "combat",
                         plot_dir_path = "plots_comparison_set2/qc/dim_red/",
                         best_features_file_path = NA,
                         dataset_replace_str = NA,
                         file_name_prefix = 6)

create_dim_red_plots_PMH(comparison = "METVsHC", classes = c("HC", "MET"),
                         omics_type = "proteomics", norm = "none",
                         dim_red = "UMAP",
                         shownames = FALSE,
                         perform_filter = FALSE,
                         batch_effect_correction = "none",
                         plot_dir_path = "plots_comparison_set2/qc/dim_red/",
                         best_features_file_path = NA,
                         dataset_replace_str = NA,
                         file_name_prefix = 7)
create_dim_red_plots_PMH(comparison = "METVsHC", classes = c("HC", "MET"),
                         omics_type = "proteomics", norm = "quantile_train_param",
                         dim_red = "UMAP",
                         shownames = FALSE,
                         perform_filter = FALSE,
                         batch_effect_correction = "none",
                         plot_dir_path = "plots_comparison_set2/qc/dim_red/",
                         best_features_file_path = NA,
                         dataset_replace_str = NA,
                         file_name_prefix = 8)




create_dim_red_plots_PMH(comparison = "PREOPEVsMET", classes = c("MET", "PREOPE"),
                         omics_type = "transcriptomics", norm = "none",
                         dim_red = "UMAP",
                         shownames = FALSE,
                         perform_filter = TRUE,
                         batch_effect_correction = "none",
                         plot_dir_path = "plots_comparison_set2/qc/dim_red/",
                         best_features_file_path = NA,
                         dataset_replace_str = NA,
                         file_name_prefix = 9)
create_dim_red_plots_PMH(comparison = "PREOPEVsMET", classes = c("MET", "PREOPE"),
                         omics_type = "transcriptomics", norm = "log_cpm",
                         dim_red = "UMAP",
                         shownames = FALSE,
                         perform_filter = TRUE,
                         batch_effect_correction = "none",
                         plot_dir_path = "plots_comparison_set2/qc/dim_red/",
                         best_features_file_path = NA,
                         dataset_replace_str = NA,
                         file_name_prefix = 10)
create_dim_red_plots_PMH(comparison = "PREOPEVsMET", classes = c("MET", "PREOPE"),
                         omics_type = "transcriptomics", norm = "log_cpm",
                         dim_red = "UMAP",
                         shownames = FALSE,
                         perform_filter = TRUE,
                         batch_effect_correction = "combat",
                         plot_dir_path = "plots_comparison_set2/qc/dim_red/",
                         best_features_file_path = NA,
                         dataset_replace_str = NA,
                         file_name_prefix = 11)

create_dim_red_plots_PMH(comparison = "PREOPEVsHC", classes = c("HC", "PREOPE"),
                         omics_type = "transcriptomics", norm = "none",
                         dim_red = "UMAP",
                         shownames = FALSE,
                         perform_filter = TRUE,
                         batch_effect_correction = "none",
                         plot_dir_path = "plots_comparison_set2/qc/dim_red/",
                         best_features_file_path = NA,
                         dataset_replace_str = NA,
                         file_name_prefix = 12)
create_dim_red_plots_PMH(comparison = "PREOPEVsHC", classes = c("HC", "PREOPE"),
                         omics_type = "transcriptomics", norm = "log_cpm",
                         dim_red = "UMAP",
                         shownames = FALSE,
                         perform_filter = TRUE,
                         batch_effect_correction = "none",
                         plot_dir_path = "plots_comparison_set2/qc/dim_red/",
                         best_features_file_path = NA,
                         dataset_replace_str = NA,
                         file_name_prefix = 13)
create_dim_red_plots_PMH(comparison = "PREOPEVsHC", classes = c("HC", "PREOPE"),
                         omics_type = "transcriptomics", norm = "log_cpm",
                         dim_red = "UMAP",
                         shownames = FALSE,
                         perform_filter = TRUE,
                         batch_effect_correction = "combat",
                         plot_dir_path = "plots_comparison_set2/qc/dim_red/",
                         best_features_file_path = NA,
                         dataset_replace_str = NA,
                         file_name_prefix = 14)

create_dim_red_plots_PMH(comparison = "METVsHC", classes = c("HC", "MET"),
                         omics_type = "transcriptomics", norm = "none",
                         dim_red = "UMAP",
                         shownames = FALSE,
                         perform_filter = TRUE,
                         batch_effect_correction = "none",
                         plot_dir_path = "plots_comparison_set2/qc/dim_red/",
                         best_features_file_path = NA,
                         dataset_replace_str = NA,
                         file_name_prefix = 15)
create_dim_red_plots_PMH(comparison = "METVsHC", classes = c("HC", "MET"),
                         omics_type = "transcriptomics", norm = "log_cpm",
                         dim_red = "UMAP",
                         shownames = FALSE,
                         perform_filter = TRUE,
                         batch_effect_correction = "none",
                         plot_dir_path = "plots_comparison_set2/qc/dim_red/",
                         best_features_file_path = NA,
                         dataset_replace_str = NA,
                         file_name_prefix = 16)


