base_dir <- "/home/abhivij/UNSW/VafaeeLab/GBMPlasmaEV"
setwd(base_dir)

source("scripts/R/qc.R")


comparison = "PREOPEVsHC"
classes = c("HC", "PREOPE")
omics_type = "transcriptomics"
norm = "log_cpm"
perform_filter = TRUE
batch_effect_correction = "combat"
plot_dir_path = "plots_comparison_set2/qc/expression_feature_level"

create_per_feature_or_sample_plot(comparison = "PREOPEVsHC",
                                  classes = c("HC", "PREOPE"),
                                  omics_type = "transcriptomics",
                                  norm = "none",
                                  perform_filter = TRUE,
                                  batch_effect_correction = "none",
                                  plot_dir_path = "plots_comparison_set2/qc/expression_feature_level")
create_per_feature_or_sample_plot(comparison = "PREOPEVsHC",
                                  classes = c("HC", "PREOPE"),
                                  omics_type = "transcriptomics",
                                  norm = "log_cpm",
                                  perform_filter = TRUE,
                                  batch_effect_correction = "none",
                                  plot_dir_path = "plots_comparison_set2/qc/expression_feature_level")
create_per_feature_or_sample_plot(comparison = "PREOPEVsHC",
                                  classes = c("HC", "PREOPE"),
                                  omics_type = "transcriptomics",
                                  norm = "log_cpm",
                                  perform_filter = TRUE,
                                  batch_effect_correction = "combat",
                                  plot_dir_path = "plots_comparison_set2/qc/expression_feature_level")
create_per_feature_or_sample_plot(comparison = "PREOPEVsMET",
                                  classes = c("MET", "PREOPE"),
                                  omics_type = "transcriptomics",
                                  norm = "none",
                                  perform_filter = TRUE,
                                  batch_effect_correction = "none",
                                  plot_dir_path = "plots_comparison_set2/qc/expression_feature_level")
create_per_feature_or_sample_plot(comparison = "PREOPEVsMET",
                                  classes = c("MET", "PREOPE"),
                                  omics_type = "transcriptomics",
                                  norm = "log_cpm",
                                  perform_filter = TRUE,
                                  batch_effect_correction = "none",
                                  plot_dir_path = "plots_comparison_set2/qc/expression_feature_level")
create_per_feature_or_sample_plot(comparison = "PREOPEVsMET",
                                  classes = c("MET", "PREOPE"),
                                  omics_type = "transcriptomics",
                                  norm = "log_cpm",
                                  perform_filter = TRUE,
                                  batch_effect_correction = "combat",
                                  plot_dir_path = "plots_comparison_set2/qc/expression_feature_level")


create_per_feature_or_sample_plot(comparison = "PREOPEVsHC",
                                  classes = c("HC", "PREOPE"),
                                  omics_type = "proteomics",
                                  norm = "none",
                                  perform_filter = FALSE,
                                  batch_effect_correction = "none",
                                  plot_dir_path = "plots_comparison_set2/qc/expression_feature_level")
create_per_feature_or_sample_plot(comparison = "PREOPEVsHC",
                                  classes = c("HC", "PREOPE"),
                                  omics_type = "proteomics",
                                  norm = "quantile",
                                  perform_filter = FALSE,
                                  batch_effect_correction = "none",
                                  plot_dir_path = "plots_comparison_set2/qc/expression_feature_level")
create_per_feature_or_sample_plot(comparison = "PREOPEVsHC",
                                  classes = c("HC", "PREOPE"),
                                  omics_type = "proteomics",
                                  norm = "quantile",
                                  perform_filter = FALSE,
                                  batch_effect_correction = "combat",
                                  plot_dir_path = "plots_comparison_set2/qc/expression_feature_level")
create_per_feature_or_sample_plot(comparison = "PREOPEVsMET",
                                  classes = c("MET", "PREOPE"),
                                  omics_type = "proteomics",
                                  norm = "none",
                                  perform_filter = FALSE,
                                  batch_effect_correction = "none",
                                  plot_dir_path = "plots_comparison_set2/qc/expression_feature_level")
create_per_feature_or_sample_plot(comparison = "PREOPEVsMET",
                                  classes = c("MET", "PREOPE"),
                                  omics_type = "proteomics",
                                  norm = "quantile",
                                  perform_filter = FALSE,
                                  batch_effect_correction = "none",
                                  plot_dir_path = "plots_comparison_set2/qc/expression_feature_level")
create_per_feature_or_sample_plot(comparison = "PREOPEVsMET",
                                  classes = c("MET", "PREOPE"),
                                  omics_type = "proteomics",
                                  norm = "quantile",
                                  perform_filter = FALSE,
                                  batch_effect_correction = "combat",
                                  plot_dir_path = "plots_comparison_set2/qc/expression_feature_level")


comparison = "PREOPEVsMET"
classes = c("MET", "PREOPE")
omics_type = "transcriptomics"
norm = "log_cpm"
perform_filter = TRUE
batch_effect_correction = "none"
plot_dir_path = "plots_RNA_all/qc/expression_feature_level/"
data_file_path = "Data/RNA_all/newquant_Nov2023_umi_counts_PREOPE_MET_HC_filter90.csv"
validation_data_file_path = "Data/RNA_all/newquant_Nov2023_umi_counts_PREOPE_MET_HC_filter90.csv"
phenotype_file_path = "Data/transcriptomic_phenotype_PREOPE_MET_HC.txt"
file_name_prefix = 1


create_per_feature_or_sample_plot(comparison = "PREOPEVsMET",
                                  classes = c("MET", "PREOPE"),
                                  omics_type = "transcriptomics",
                                  norm = "none",
                                  perform_filter = TRUE,
                                  batch_effect_correction = "none",
                                  plot_dir_path = "plots_RNA_all/PREOPE_MET_HC/qc/expression_feature_level/",
                                  data_file_path = "Data/RNA_all/newquant_Nov2023_umi_counts_PREOPE_MET_HC_filter90.csv",
                                  validation_data_file_path = "Data/RNA_all/newquant_Nov2023_umi_counts_PREOPE_MET_HC_filter90.csv",
                                  phenotype_file_path = "Data/transcriptomic_phenotype_PREOPE_MET_HC.txt")
create_per_feature_or_sample_plot(comparison = "PREOPEVsMET",
                                  classes = c("MET", "PREOPE"),
                                  omics_type = "transcriptomics",
                                  norm = "log_cpm",
                                  perform_filter = TRUE,
                                  batch_effect_correction = "none",
                                  plot_dir_path = "plots_RNA_all/PREOPE_MET_HC/qc/expression_feature_level/",
                                  data_file_path = "Data/RNA_all/newquant_Nov2023_umi_counts_PREOPE_MET_HC_filter90.csv",
                                  validation_data_file_path = "Data/RNA_all/newquant_Nov2023_umi_counts_PREOPE_MET_HC_filter90.csv",
                                  phenotype_file_path = "Data/transcriptomic_phenotype_PREOPE_MET_HC.txt")
create_per_feature_or_sample_plot(comparison = "PREOPEVsMET",
                                  classes = c("MET", "PREOPE"),
                                  omics_type = "transcriptomics",
                                  norm = "log_cpm",
                                  perform_filter = TRUE,
                                  batch_effect_correction = "combat",
                                  plot_dir_path = "plots_RNA_all/PREOPE_MET_HC/qc/expression_feature_level/",
                                  data_file_path = "Data/RNA_all/newquant_Nov2023_umi_counts_PREOPE_MET_HC_filter90.csv",
                                  validation_data_file_path = "Data/RNA_all/newquant_Nov2023_umi_counts_PREOPE_MET_HC_filter90.csv",
                                  phenotype_file_path = "Data/transcriptomic_phenotype_PREOPE_MET_HC.txt")


create_per_feature_or_sample_plot(comparison = "PREOPEVsHC",
                                  classes = c("HC", "PREOPE"),
                                  omics_type = "transcriptomics",
                                  norm = "none",
                                  perform_filter = TRUE,
                                  batch_effect_correction = "none",
                                  plot_dir_path = "plots_RNA_all/PREOPE_MET_HC/qc/expression_feature_level/",
                                  data_file_path = "Data/RNA_all/newquant_Nov2023_umi_counts_PREOPE_MET_HC_filter90.csv",
                                  validation_data_file_path = "Data/RNA_all/newquant_Nov2023_umi_counts_PREOPE_MET_HC_filter90.csv",
                                  phenotype_file_path = "Data/transcriptomic_phenotype_PREOPE_MET_HC.txt")
create_per_feature_or_sample_plot(comparison = "PREOPEVsHC",
                                  classes = c("HC", "PREOPE"),
                                  omics_type = "transcriptomics",
                                  norm = "log_cpm",
                                  perform_filter = TRUE,
                                  batch_effect_correction = "none",
                                  plot_dir_path = "plots_RNA_all/PREOPE_MET_HC/qc/expression_feature_level/",
                                  data_file_path = "Data/RNA_all/newquant_Nov2023_umi_counts_PREOPE_MET_HC_filter90.csv",
                                  validation_data_file_path = "Data/RNA_all/newquant_Nov2023_umi_counts_PREOPE_MET_HC_filter90.csv",
                                  phenotype_file_path = "Data/transcriptomic_phenotype_PREOPE_MET_HC.txt")
create_per_feature_or_sample_plot(comparison = "PREOPEVsHC",
                                  classes = c("HC", "PREOPE"),
                                  omics_type = "transcriptomics",
                                  norm = "log_cpm",
                                  perform_filter = TRUE,
                                  batch_effect_correction = "combat",
                                  plot_dir_path = "plots_RNA_all/PREOPE_MET_HC/qc/expression_feature_level/",
                                  data_file_path = "Data/RNA_all/newquant_Nov2023_umi_counts_PREOPE_MET_HC_filter90.csv",
                                  validation_data_file_path = "Data/RNA_all/newquant_Nov2023_umi_counts_PREOPE_MET_HC_filter90.csv",
                                  phenotype_file_path = "Data/transcriptomic_phenotype_PREOPE_MET_HC.txt")


create_per_feature_or_sample_plot(comparison = "METVsHC",
                                  classes = c("HC", "MET"),
                                  omics_type = "transcriptomics",
                                  norm = "none",
                                  perform_filter = TRUE,
                                  batch_effect_correction = "none",
                                  plot_dir_path = "plots_RNA_all/PREOPE_MET_HC/qc/expression_feature_level/",
                                  data_file_path = "Data/RNA_all/newquant_Nov2023_umi_counts_PREOPE_MET_HC_filter90.csv",
                                  validation_data_file_path = "Data/RNA_all/newquant_Nov2023_umi_counts_PREOPE_MET_HC_filter90.csv",
                                  phenotype_file_path = "Data/transcriptomic_phenotype_PREOPE_MET_HC.txt")
create_per_feature_or_sample_plot(comparison = "METVsHC",
                                  classes = c("HC", "MET"),
                                  omics_type = "transcriptomics",
                                  norm = "log_cpm",
                                  perform_filter = TRUE,
                                  batch_effect_correction = "none",
                                  plot_dir_path = "plots_RNA_all/PREOPE_MET_HC/qc/expression_feature_level/",
                                  data_file_path = "Data/RNA_all/newquant_Nov2023_umi_counts_PREOPE_MET_HC_filter90.csv",
                                  validation_data_file_path = "Data/RNA_all/newquant_Nov2023_umi_counts_PREOPE_MET_HC_filter90.csv",
                                  phenotype_file_path = "Data/transcriptomic_phenotype_PREOPE_MET_HC.txt")





create_per_feature_or_sample_plot(comparison = "PREOPEVsMET",
                                  classes = c("MET", "PREOPE"),
                                  omics_type = "transcriptomics",
                                  norm = "none",
                                  perform_filter = TRUE,
                                  batch_effect_correction = "none",
                                  plot_dir_path = "plots_RNA_all/PREOPE_MET_HC/qc/expression_sample_level",
                                  data_file_path = "Data/RNA_all/newquant_Nov2023_umi_counts_PREOPE_MET_HC_filter90.csv",
                                  validation_data_file_path = "Data/RNA_all/newquant_Nov2023_umi_counts_PREOPE_MET_HC_filter90.csv",
                                  phenotype_file_path = "Data/transcriptomic_phenotype_PREOPE_MET_HC.txt", 
                                  plot_type = "per_sample")
create_per_feature_or_sample_plot(comparison = "PREOPEVsMET",
                                  classes = c("MET", "PREOPE"),
                                  omics_type = "transcriptomics",
                                  norm = "log_cpm",
                                  perform_filter = TRUE,
                                  batch_effect_correction = "none",
                                  plot_dir_path = "plots_RNA_all/PREOPE_MET_HC/qc/expression_sample_level",
                                  data_file_path = "Data/RNA_all/newquant_Nov2023_umi_counts_PREOPE_MET_HC_filter90.csv",
                                  validation_data_file_path = "Data/RNA_all/newquant_Nov2023_umi_counts_PREOPE_MET_HC_filter90.csv",
                                  phenotype_file_path = "Data/transcriptomic_phenotype_PREOPE_MET_HC.txt", 
                                  plot_type = "per_sample")
create_per_feature_or_sample_plot(comparison = "PREOPEVsMET",
                                  classes = c("MET", "PREOPE"),
                                  omics_type = "transcriptomics",
                                  norm = "log_cpm",
                                  perform_filter = TRUE,
                                  batch_effect_correction = "combat",
                                  plot_dir_path = "plots_RNA_all/PREOPE_MET_HC/qc/expression_sample_level",
                                  data_file_path = "Data/RNA_all/newquant_Nov2023_umi_counts_PREOPE_MET_HC_filter90.csv",
                                  validation_data_file_path = "Data/RNA_all/newquant_Nov2023_umi_counts_PREOPE_MET_HC_filter90.csv",
                                  phenotype_file_path = "Data/transcriptomic_phenotype_PREOPE_MET_HC.txt", 
                                  plot_type = "per_sample")


create_per_feature_or_sample_plot(comparison = "PREOPEVsHC",
                                  classes = c("HC", "PREOPE"),
                                  omics_type = "transcriptomics",
                                  norm = "none",
                                  perform_filter = TRUE,
                                  batch_effect_correction = "none",
                                  plot_dir_path = "plots_RNA_all/PREOPE_MET_HC/qc/expression_sample_level",
                                  data_file_path = "Data/RNA_all/newquant_Nov2023_umi_counts_PREOPE_MET_HC_filter90.csv",
                                  validation_data_file_path = "Data/RNA_all/newquant_Nov2023_umi_counts_PREOPE_MET_HC_filter90.csv",
                                  phenotype_file_path = "Data/transcriptomic_phenotype_PREOPE_MET_HC.txt", 
                                  plot_type = "per_sample")
create_per_feature_or_sample_plot(comparison = "PREOPEVsHC",
                                  classes = c("HC", "PREOPE"),
                                  omics_type = "transcriptomics",
                                  norm = "log_cpm",
                                  perform_filter = TRUE,
                                  batch_effect_correction = "none",
                                  plot_dir_path = "plots_RNA_all/PREOPE_MET_HC/qc/expression_sample_level",
                                  data_file_path = "Data/RNA_all/newquant_Nov2023_umi_counts_PREOPE_MET_HC_filter90.csv",
                                  validation_data_file_path = "Data/RNA_all/newquant_Nov2023_umi_counts_PREOPE_MET_HC_filter90.csv",
                                  phenotype_file_path = "Data/transcriptomic_phenotype_PREOPE_MET_HC.txt", 
                                  plot_type = "per_sample")
create_per_feature_or_sample_plot(comparison = "PREOPEVsHC",
                                  classes = c("HC", "PREOPE"),
                                  omics_type = "transcriptomics",
                                  norm = "log_cpm",
                                  perform_filter = TRUE,
                                  batch_effect_correction = "combat",
                                  plot_dir_path = "plots_RNA_all/PREOPE_MET_HC/qc/expression_sample_level",
                                  data_file_path = "Data/RNA_all/newquant_Nov2023_umi_counts_PREOPE_MET_HC_filter90.csv",
                                  validation_data_file_path = "Data/RNA_all/newquant_Nov2023_umi_counts_PREOPE_MET_HC_filter90.csv",
                                  phenotype_file_path = "Data/transcriptomic_phenotype_PREOPE_MET_HC.txt", 
                                  plot_type = "per_sample")


create_per_feature_or_sample_plot(comparison = "METVsHC",
                                  classes = c("HC", "MET"),
                                  omics_type = "transcriptomics",
                                  norm = "none",
                                  perform_filter = TRUE,
                                  batch_effect_correction = "none",
                                  plot_dir_path = "plots_RNA_all/PREOPE_MET_HC/qc/expression_sample_level",
                                  data_file_path = "Data/RNA_all/newquant_Nov2023_umi_counts_PREOPE_MET_HC_filter90.csv",
                                  validation_data_file_path = "Data/RNA_all/newquant_Nov2023_umi_counts_PREOPE_MET_HC_filter90.csv",
                                  phenotype_file_path = "Data/transcriptomic_phenotype_PREOPE_MET_HC.txt", 
                                  plot_type = "per_sample")
create_per_feature_or_sample_plot(comparison = "METVsHC",
                                  classes = c("HC", "MET"),
                                  omics_type = "transcriptomics",
                                  norm = "log_cpm",
                                  perform_filter = TRUE,
                                  batch_effect_correction = "none",
                                  plot_dir_path = "plots_RNA_all/PREOPE_MET_HC/qc/expression_sample_level",
                                  data_file_path = "Data/RNA_all/newquant_Nov2023_umi_counts_PREOPE_MET_HC_filter90.csv",
                                  validation_data_file_path = "Data/RNA_all/newquant_Nov2023_umi_counts_PREOPE_MET_HC_filter90.csv",
                                  phenotype_file_path = "Data/transcriptomic_phenotype_PREOPE_MET_HC.txt", 
                                  plot_type = "per_sample")
