#!/bin/bash

#PBS -l select=1:ncpus=8:mem=16gb
#PBS -l walltime=12:00:00

source $(conda info --base)/etc/profile.d/conda.sh
conda activate cutadaptenv

cd /srv/scratch/vafaeelab/AbhishekVijayan/GBMPlasmaEV/Data/

mkdir trimmedRNA

for fn in RNA/*fastq.gz;
do
samp=`basename ${fn}`
echo "Trimming and filtering sample ${samp}"
cutadapt -a AACTGTAGGCACCATCAAT -m 1 -M 30 --cores=8 -o trimmedRNA/${samp} ${fn}
done